ergastdb:
  container_name: workshop-db
  build: ergastdb/
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: f1
    MYSQL_DATABASE: ergastdb
  expose:
    - "3306"


web:
  container_name: workshop-f1-api
  build: ./lamp
  restart: always
  ports:
    - '8001:80'
    - '8002:80'
  volumes:
    - ./webroot:/var/www/html
    - ./php/api:/php/api
    - ./logs:/var/log/apache2
  links:
    - ergastdb:ergastdb
  
#docker-compose up --build -d
#docker-compose build --force-rm
#docker-compose up -d

